const games=[{name:'Circle Accuracy',active:true,class:'circle-card'},{name:'Reaction Rush',emoji:'⚡',color:'#ff9b6b'},{name:'Memory Match',emoji:'🧠',color:'#58b9d0'},{name:'Line Sprint',emoji:'📏',color:'#d075c6'},{name:'Color Pop',emoji:'🎨',color:'#86bc68'},{name:'Cup Toss',emoji:'🏓',color:'#e2b656'}];
const modes=[{id:'classic',icon:'∞',tint:'#eeeaff',title:'CLASSIC',text:'No rush. Take your time and find your flow.'},{id:'challenge',icon:'3',tint:'#ffe9f0',title:'3-SECOND CHALLENGE',text:'Three seconds. One brilliant orbit.'},{id:'speed',icon:'↯',tint:'#e2f8f6',title:'SPEED MODE',text:'Draw accurately, then race your time.'}];
const $=s=>document.querySelector(s), screens=document.querySelectorAll('.screen');let mode='classic',points=[],drawing=false,startedAt=0,elapsed=0,challengeTimer,gameReady=false;
const bestKey='orbit-circle-best';const getBest=()=>Number(localStorage.getItem(bestKey)||0);const fmt=n=>`${n.toFixed(2)}%`;
function show(id){screens.forEach(s=>s.classList.toggle('active',s.id===id));window.scrollTo(0,0);if(id==='modes') updateBest();}
function updateBest(){const b=getBest();$('#modeBest').textContent=b?fmt(b):'NO SCORE YET'}
function renderHome(){ $('#gameGrid').innerHTML=games.map(g=>g.active?`<button class="game-card circle-card" id="openCircle"><div class="circle-art"></div><h3>${g.name}<small>DRAW TO WIN</small></h3></button>`:`<button class="game-card soon" disabled style="--bg:${g.color}"><span class="emoji">${g.emoji}</span><h3>${g.name}<small>COMING SOON</small></h3></button>`).join('');$('#openCircle').onclick=()=>show('modes');}
function renderModes(){$('#modeList').innerHTML=modes.map(m=>`<button class="mode-card" data-mode="${m.id}"><span class="mode-icon" style="--tint:${m.tint}">${m.icon}</span><span><h3>${m.title}</h3><p>${m.text}</p></span><b class="arrow">›</b></button>`).join('');document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>startGame(b.dataset.mode));}
const canvas=$('#drawCanvas'),ctx=canvas.getContext('2d');function fitCanvas(c){const rect=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);c.width=rect.width*dpr;c.height=rect.height*dpr;return {w:rect.width,h:rect.height,dpr}}
function setupCanvas(){let {dpr}=fitCanvas(canvas);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#f36aa3';ctx.lineWidth=5;}
function clear(){points=[];ctx.clearRect(0,0,canvas.width,canvas.height);$('#drawHint').textContent='Draw one complete loop, then lift your finger.'}
async function countdown(){const el=$('#countdown');el.classList.add('show');for(const n of ['3','2','1','GO!']){el.textContent=n;await new Promise(r=>setTimeout(r,n==='GO!'?500:700));}el.classList.remove('show');gameReady=true;startedAt=performance.now();$('#timer').textContent='3 SECONDS';challengeTimer=setTimeout(()=>finish(),3000)}
function startGame(nextMode){mode=nextMode;show('play');setupCanvas();clear();gameReady=mode==='classic'||mode==='speed';$('#modeLabel').textContent=modes.find(m=>m.id===mode).title;$('#timer').textContent=mode==='speed'?'00.00 s':'DRAW A CIRCLE';$('#finishButton').style.display=mode==='challenge'?'none':'';if(mode==='challenge') countdown();else if(mode==='classic') startedAt=performance.now();}
function point(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top,t:performance.now()}}
canvas.addEventListener('pointerdown',e=>{if(!gameReady)return;e.preventDefault();canvas.setPointerCapture(e.pointerId);drawing=true;const p=point(e);points=[p];startedAt=mode==='speed'?p.t:startedAt;ctx.beginPath();ctx.moveTo(p.x,p.y);});canvas.addEventListener('pointermove',e=>{if(!drawing||!gameReady)return;e.preventDefault();const p=point(e),last=points[points.length-1];if(Math.hypot(p.x-last.x,p.y-last.y)<1.5)return;points.push(p);ctx.lineTo(p.x,p.y);ctx.stroke();});canvas.addEventListener('pointerup',e=>{if(!drawing)return;drawing=false;elapsed=performance.now()-startedAt;if(mode!=='classic') finish();else $('#drawHint').textContent='Nice trace! Tap Finish Drawing when you are ready.'});canvas.addEventListener('pointercancel',()=>drawing=false);
function scoreDrawing(){const rect=canvas.getBoundingClientRect(),target={x:rect.width/2,y:rect.height/2};if(points.length<12)return null;const n=points.length,first=points[0],last=points[n-1];let cx=0,cy=0;points.forEach(p=>{cx+=p.x;cy+=p.y});cx/=n;cy/=n;const radii=points.map(p=>Math.hypot(p.x-cx,p.y-cy)),radius=radii.reduce((a,b)=>a+b,0)/n;if(radius<18)return null;const dev=Math.sqrt(radii.reduce((s,r)=>s+(r-radius)**2,0)/n)/radius;const centerDist=Math.hypot(cx-target.x,cy-target.y);const closure=Math.hypot(last.x-first.x,last.y-first.y)/radius;let totalAngle=0,prev=Math.atan2(points[0].y-cy,points[0].x-cx),sign=0,turns=0;for(let i=1;i<n;i++){let a=Math.atan2(points[i].y-cy,points[i].x-cx),d=a-prev;while(d>Math.PI)d-=2*Math.PI;while(d<-Math.PI)d+=2*Math.PI;if(Math.abs(d)>.01){if(!sign)sign=Math.sign(d);if(Math.sign(d)===sign)turns+=Math.abs(d);else turns-=Math.abs(d)*.4}prev=a;}totalAngle=turns;const completeness=Math.min(1,totalAngle/(Math.PI*2));let jag=0;for(let i=2;i<n;i++){const a=Math.atan2(points[i-2].y-cy,points[i-2].x-cx),b=Math.atan2(points[i-1].y-cy,points[i-1].x-cx),c=Math.atan2(points[i].y-cy,points[i].x-cx);let d1=b-a,d2=c-b;while(d1>Math.PI)d1-=2*Math.PI;while(d1<-Math.PI)d1+=2*Math.PI;while(d2>Math.PI)d2-=2*Math.PI;while(d2<-Math.PI)d2+=2*Math.PI;jag+=Math.abs(d2-d1)}jag/=Math.max(1,n-2);const consistency=Math.exp(-4.1*dev),center=Math.exp(-2.7*centerDist/radius),complete=Math.max(0,Math.min(1,completeness))*Math.exp(-1.7*closure),smooth=Math.exp(-5*jag);let score=100*(.39*consistency+.31*center+.20*complete+.10*smooth);score=Math.max(0,Math.min(99.92,score));return{score,center,consistency,complete,smooth,radius,cx,cy,target,centerDist};}
function finish(){if(!gameReady&&mode==='challenge')return;clearTimeout(challengeTimer);gameReady=false;drawing=false;elapsed=elapsed||performance.now()-startedAt;const data=scoreDrawing();if(!data){toast('Trace a full circle before finishing.');if(mode==='challenge')setTimeout(()=>startGame(mode),900);return;}showResult(data)}
function showResult(d){const old=getBest(),newBest=d.score>old;if(newBest)localStorage.setItem(bestKey,d.score.toFixed(2));$('#mainScore').textContent=fmt(d.score);$('#newBest').classList.toggle('show',newBest);$('#resultMessage').textContent=d.score>=95?'PERFECT! 🔥':d.score>=90?'Excellent! 🏆':d.score>=80?'Great!':d.score>=70?'Good!':'Keep Practicing!';let insight=d.center<.7?'Your circle was slightly off-center.':d.complete<.78?'Your circle was very consistent, but incomplete.':d.consistency<.75?'Great center placement, but the radius varied.':'A wonderfully balanced orbit.';$('#insight').textContent=insight;const stats=[['CENTER',fmt(d.center*100)],['CONSISTENCY',fmt(d.consistency*100)],['COMPLETE',fmt(d.complete*100)],['RADIUS',`${Math.round(d.radius)} px`],['TIME',`${(elapsed/1000).toFixed(2)} s`],['BEST',fmt(Math.max(d.score,old))]];$('#statGrid').innerHTML=stats.map(s=>`<div class="stat"><b>${s[1]}</b><small>${s[0]}</small></div>`).join('');drawResult(d);show('results');}
function drawResult(d){const c=$('#resultCanvas'),ctx2=c.getContext('2d'),r=c.getBoundingClientRect(),q=Math.min(devicePixelRatio||1,2);c.width=r.width*q;c.height=r.height*q;ctx2.setTransform(q,0,0,q,0,0);const scale=r.width/canvas.getBoundingClientRect().width,center={x:r.width/2,y:r.height/2};ctx2.strokeStyle='#48c8d7';ctx2.setLineDash([5,5]);ctx2.lineWidth=2;ctx2.beginPath();ctx2.arc(center.x,center.y,d.radius*scale,0,Math.PI*2);ctx2.stroke();ctx2.setLineDash([]);ctx2.strokeStyle='#f36aa3';ctx2.lineWidth=3;ctx2.lineCap='round';ctx2.lineJoin='round';ctx2.beginPath();points.forEach((p,i)=>{const x=p.x*scale,y=p.y*scale;i?ctx2.lineTo(x,y):ctx2.moveTo(x,y)});ctx2.stroke();}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
$('#finishButton').onclick=finish;$('#clearCanvas').onclick=clear;$('#quitGame').onclick=()=>{clearTimeout(challengeTimer);show('modes')};document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#retryButton').onclick=()=>startGame(mode);$('#shareButton').onclick=async()=>{const message=`I scored ${$('#mainScore').textContent} on Circle Accuracy! 🎯 Can you beat me?`;try{if(navigator.share)await navigator.share({title:'Circle Accuracy',text:message,url:location.href});else{await navigator.clipboard.writeText(message);toast('Score copied to clipboard!')}}catch(e){if(e.name!=='AbortError')toast('Could not share this score.')}};$('#statsButton').onclick=()=>toast(getBest()?`Circle Accuracy best: ${fmt(getBest())}`:'Play Circle Accuracy to set a best!');renderHome();renderModes();
